[package]
name = "chd"
version = "0.0.1"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
edition = "2018"
description = "Rust implementation of the CHD File Format"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
