[package]
name = "chd-capi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[features]
default = ["chd_core_file"]
chd_core_file = ["bindgen", "cmake"]

[dependencies]
chd = "0.0.9"

[build-dependencies]
cbindgen = "0.23.0"
bindgen = { version = "0.59.2", optional = true }
cmake = { version =  "0.1.48", optional = true }