[package]
name = "chd"
version = "0.0.3"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
edition = "2021"
description = "Rust implementation of the CHD File Format"
license = "BSD-3-Clause"
repository = "https://github.com/SnowflakePowered/chd-rs"
readme = "../README.md"
categories = ["emulators", "compression", "encoding"]
keywords = ["mame", "chd", "decompression"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["want_subcode", "want_raw_data_sector"]
verify_block_crc = []
want_subcode = []
want_raw_data_sector = []
avhuff = []

[dependencies]
byteorder = "1"
num-traits = "0.2"
num-derive = "0.3"
regex = { version = "1", features = ["std", "perf"] }
lazy_static = "1.4.0"
flate2 = "1"
lzma-rs-headerless = "0.2.1"
claxon = "0.4"
bitreader = "0.3.4"
crc = "3"
cfg-if = "1"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "bench"
harness = false
