[package]
name = "chd"
version = "0.0.2"
authors = ["Ronny Chan <ronny@ronnychan.ca>"]
edition = "2021"
description = "Rust implementation of the CHD File Format"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["want_subcode", "want_raw_data_sector"]
verify_block_crc = []
want_subcode = []
want_raw_data_sector = []

[dependencies]
byteorder = "1"
num-traits = "0.2"
num-derive = "0.3"
regex = "1"
lazy_static = "1.4.0"
flate2 = "1"
lzma-rs = { path = "../lzma-rs" }
claxon = "0.4"
bitreader = "0.3.4"
crc = "3"
cfg-if = "1"